{
  "name": "SupplyChainSample",
  "id": "SupplyChainSample",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_6de7953b-39de-41ab-b96b-cebbc3f3ccc1",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "4b2421c5-3c4c-4f5c-bd09-d90782719653",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "a038f861-30a2-4abd-9ae2-412f386b2d3a",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "10575e0a-6696-4125-8b99-355a0a46db49",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "e75a5b28-623b-484a-9818-25d4deac204b",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "69c2a15c-779c-4dac-aee1-e90b045d3229",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "52a0d31b-78f3-4876-ae9e-e87445206edb",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "c3f465e3-c22a-4dbe-a6e8-9873625bf6a6",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "c1476539-9722-43b4-9fd7-517643d6291a",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_6de7953b-39de-41ab-b96b-cebbc3f3ccc1-9020e431-9ac3-456e-b5d4-e0b3c7ba7ac8",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "a7f76605-3c58-4643-abf0-0e0c22cb84e2",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "2d636b71-56fc-4379-a4b0-dd1ba0fc13ff"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "0185c394-aa95-4bba-9af7-69923e974785"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "1b9a257c-0960-4ea1-a037-04a6dff76575"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "f65f8ab6-0267-430e-8317-7b0337f54d2e"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "Supply Analytics",
        "lineageTag": "44e94bd4-6ef1-40c1-8df6-569588318647",
        "columns": [
          {
            "name": "Manufactured Goods %",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Manufactured Goods %",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4764b380-f9a8-4da2-b475-82ce0acaf8bf",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Forecast Accuracy",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Forecast Accuracy",
            "displayFolder": "Influencers",
            "lineageTag": "ed866b14-aedf-4870-846b-e6f39bf4fb2c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Forecast Bias",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Forecast Bias",
            "displayFolder": "Influencers",
            "lineageTag": "45ef6f81-c169-48b8-a820-f145c7a31d2a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Product Advertised",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Advertised",
            "lineageTag": "7f310e4e-2fa8-4ac6-8058-5d8ccf176d7a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Multiple Retailers",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Multiple Retailers",
            "lineageTag": "f20e3666-aa9f-44f1-b4ad-d3cede226694",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Day Contacted",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Day Contacted",
            "formatString": "0",
            "lineageTag": "79eb6298-959f-4680-8954-045763605ebd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Product ",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product ",
            "lineageTag": "e453e737-f83f-47dd-8d73-ef9faffd341e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Manufactured (%)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "If('Supply Analytics'[Manufactured Goods %] <=0.9, \">125%\", if('Supply Analytics'[Manufactured Goods %] >0.9 && [Manufactured Goods %] <= 1.2, \"Between 100%-125%\", if('Supply Analytics'[Manufactured Goods %] > 1.2 && [Manufactured Goods %] <= 1.2, \"Between 75%-100%\", \"<75%\")))",
            "lineageTag": "25310a24-3b96-4748-828c-d9e4994f27d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Inventory Levels",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Inventory Levels",
            "lineageTag": "6fd1745f-cd6b-45cd-8268-fd07b70194cc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Manufactured Goods",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "If('Supply Analytics'[Manufactured Goods %] <=1.1, \">100%\", \"<70%\")",
            "displayFolder": "Influencers",
            "lineageTag": "f3ddad61-dec1-49ca-bc82-e9124b1a9310",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Demand Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Demand Type",
            "displayFolder": "Influencers",
            "lineageTag": "231a806e-5ba7-4b18-bf65-7b9aa53451a1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Manufactured Goods (%)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Manufactured Goods (%)",
            "lineageTag": "d3c895b4-93b4-4d03-9cc5-6a18da4336b4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Type",
            "lineageTag": "3a8504f4-708e-4c56-bd40-b64bef8e3ab7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Plant",
            "lineageTag": "b9973e23-6344-4976-8bd5-fadd325bc7f3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Supply Analytics-b415f3eb-76cb-4172-90fb-8e97ed3589f0",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Justyna\\Documents\\MBAS 2019\\Backorders2.xlsx\"), null, true),",
                "    #\"bank-full2_Sheet\" = Source{[Item=\"Backorders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"bank-full2_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Manufactured Goods %\", type number}, {\"Demand Type\", type text}, {\"Forecast Accuracy\", type text}, {\"Forecast Bias\", type text}, {\"Product Advertised\", type text}, {\"Multiple Retailers\", type text}, {\"Type\", type text}, {\"Day Contacted\", Int64.Type}, {\"Plant\", type text}, {\"Product \", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Manufactured Goods\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6a570876-50cb-4351-a1c2-3b1ea0291c67"
          },
          {
            "name": "LinkedQueryName",
            "value": "Supply Analytics"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "Risk",
        "isHidden": true,
        "lineageTag": "68ad9184-c8e1-49f4-a295-3c1f1e951a11",
        "columns": [
          {
            "name": "Product ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product ID",
            "formatString": "0",
            "lineageTag": "14a8aa5d-8cbc-4a9d-9e02-e4f1173070ac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Location",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Location",
            "lineageTag": "89d547c2-2695-4f88-8de4-ba3257ef231a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Risk Score",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Risk Score",
            "lineageTag": "3d9ce1cb-f2e4-49e8-b965-f00194b93d94",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Backorder Risk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Backorder Risk",
            "formatString": "0",
            "lineageTag": "3552c320-4b7b-43e3-b7d1-d9ffc900a598",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Distribution Center",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distribution Center",
            "lineageTag": "aec44d1f-3034-410d-840a-d1da3c9afc76",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Risk-d9078ef0-04f1-4c0d-a009-616523a3fc04",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(AzureStorage.BlobContents(\"https://demostoragepbi.blob.core.windows.net/demo/automl%20demo.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product ID\", Int64.Type}, {\"Location\", type text}, {\"Risk Score\", type text}, {\"Backorder Risk\", Int64.Type}, {\"Distribution Center\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8ecb34a8-a096-4d03-924c-c1a91b337e28"
          },
          {
            "name": "LinkedQueryName",
            "value": "Risk"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Explanations",
        "isHidden": true,
        "lineageTag": "57aef493-fda6-4408-b214-b76a85b9a080",
        "columns": [
          {
            "name": "Product ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product ID",
            "formatString": "0",
            "lineageTag": "4a6ce09d-2af9-43aa-a858-da70c56cd320",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Location",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Location",
            "lineageTag": "a6be4c50-eda5-4ee9-8d65-4b9d225bc4ef",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Factor",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Factor",
            "lineageTag": "4d0eb36a-5710-4694-a44e-40f694dc0316",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Risk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Risk",
            "formatString": "0",
            "lineageTag": "ca5b2241-a5ec-46bc-ba11-dad972ad8bdb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Explanations-da57eca1-da42-4086-8190-eab8106fff57",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\juluczni\\Documents\\Explanations.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product ID\", Int64.Type}, {\"Location\", type text}, {\"Factor\", type text}, {\"Risk\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "545aed8a-9467-4e7a-ba70-0d4936a7b9dc"
          },
          {
            "name": "LinkedQueryName",
            "value": "Explanations"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":4,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Explanations/Changed Type.{Product ID,0}\",\"Section1/Explanations/Changed Type.{Location,1}\",\"Section1/Explanations/Changed Type.{Factor,2}\",\"Section1/Explanations/Changed Type.{Risk,3}\"],\"ColumnCount\":4,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Explanations/Changed Type.{Product ID,0}\",\"Section1/Explanations/Changed Type.{Location,1}\",\"Section1/Explanations/Changed Type.{Factor,2}\",\"Section1/Explanations/Changed Type.{Risk,3}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Logo",
        "isHidden": true,
        "lineageTag": "92518f12-c1f1-4d79-b7fb-122faed5a335",
        "columns": [
          {
            "name": "URL",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "URL",
            "lineageTag": "99ff2aa4-f579-474f-8ff5-80107a49d17d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Logo-b7177523-7710-4cca-bfce-da4107d111c5",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lVnbjhvHEf2VifQiIZxh3y8UAgOJYcBAgASxlTx4/UCRs7uEyBliOHvT1+dUdfdwyF0FjgBD7Krqquq6nKqRf/vt3c2DEHrzw/NhXz22w2nXd3+5eScbcfOuartNv911dyB8/vWnOoB0Gtfddr3vuxbErr959wPfb2+6pOdPdV39bWjXY7utnnbjffVz9/W0WR/b6sP9OB5Xy+XT01Ozy8SmH+6WH6u6npRkNafHu5uuqip41Z1W2w2M5evHh2HP17abZbtvD203npaykcubd7Mbm9mNDbmze2w3/eHQdye+3J3eX8gP29vzBfLwSbOcjDEuhVoqVUOkPr104/q5vr4Nb9+8rYQQS3rKTPgPC65OiP0R/51vFEpz6h+GTXuLq23TtePyx19/nJi1aLbj9kJTCfel7YskdOtDezquN+1pWehZxdNuO95TSSjXBGmCzPT7dnd3P4KhZOOscTZmxuOuffpr/wyOqESldWOtFsFWtvEqGidDljuNL3tyaRzW3QlvOawq2N23H/RCf6yYukcdfTD2+LwIx+ePn4qBWZkWb3ZbHBFBKZ00hZYfsjpfEE1UjagGaVUs/pbArbb9hsIAsUO7HYe+222alJRcnVWVqnPb3p74arZLZxgWYS5ahDf73fGf6/E+X8hXClVKIYq/9KfQP3e7kWrl4dQOv1Be/tF9PrWX+ouF41z77NmbvuvazdgP9eZheFyPDwO9TcysZWeO2RF1wSLOoTLeNzb4hRONU6G6r6JpvHPVvyvvGqlAqDPlG+Bh+fr9yykAV1FcchiviFMyKBNbKqV5oL+sT+3k43F9h57e9wMY72/5z8T70g/bdpi4jv9ccXuEdTe+FLQrdkr0SP1ZRHxP5HS/3vZP1Aav+d/6/gCOa7Q3xlr/WmJDbeJFo633Xr/BZ/fAVz6aNyygZB8IAuuHXC+HwxtKHoaBZPbrl5bCwX/LSe503z/dDRzf2/V+FuDb3Vgf1sPdrqvH/nhROjPWvr0dv8cbMkS8yfzSjyPH58wtrzg+v37F065DoOszHIU3MpKFJmxC3L8rRKGvv89++d/sw/p5d9h9ayls8rLyUyUf2nG9XY/ref0WGqGUfAssMGRW//rxp7e6fLNZ/acfvs4alITXX/oHeug1MkxQtVkRtK7HxN4dULI0af6MyVDa8FLkDQ3jy3FGzpaHNk2ht0fzdnPY0bXlL+Nuv/+ZzF7Dw6WJ3bhvM3dya068iMWyBOM12ryKYKZP6bhi3F3nd7/+0u7xqL9Tl1TydQHcDf3D8dBv29JKZ5Ht6+6apluZdDzTaql0o4RXflErIKz2SsaPb1XEBbj/H9B+Aexhxihj9xZ5Wb1XyqyD/0SHOqPdSqbj8LBvV13ffQNUfjphHn7lY5t/p05cEXbhBd7PbaTRITVmbRTRLdCrDQA42mpTYT8RxrkF/rZB6kAEbUIkQlTKSiJEh8sXFOtssAvBTGnMguw6Z/nsnYmLIvutOlQs4yHeKOmig1WB3zI45di+tMTTPkYz+QMTcEPSQFONj8IEutYgeiyMBUdLnE10QuLsrcL0k40ymJvTGboEfOO/kVrsPm1t6CTnB6GziL2ghvnJuJiEogoUCFghb3RQMR1ZShm9qKUodzJL08Frk06W7Udz1iI0QnlWYr09S2oRfRLVkrhOkAlYlogAzsEbywRlJNvBs1lcJtVJWihBwRJOJ9VaeAQ2v27DRo1Pgt5ylH1MktZHOjthk9oQIm6SoHbVI374YGxIdWSwVlIulPGaziF4pSmxIRpf1bLRSLCbCI9VjkAqQomtRjeOPGIX/SJx2Qsny0nCjNZceqqRXjiOjo9BmxlFUskKuE4/FeqIYoMqskgeusBFPBMy2gc5J6BKyWP8Ct4J8oBawk1nXKHFASVdR+ogvEZRaWHdoqBEiyao9hQwKOZq0giKTDnmuokwlSOIqmdZ5MZzvzALbnqLSixX78mtiL7cc7BVkHO14Ljv6WWTZ7XcbjO14EQqiz13vKIQ15Za31BtIGyAA2kT20uN/ieIRFMTQVoTzuG5L12cpKVTkZ1KXL6vIvdfUlDUW0YH6Rojqb6oS7xL5RAIMSjJVDXWcidBCi85UyS9JUoqJCRIRSuTZjzYaVBLthLcqOBSyERgeEEZKaoKbdBLszNaIeEBfUK49CvYKBfljbn8dSp/i6TnCo6aq5RY1JBUbouEZtwdMpjZESgtMoAGfJCxeqTD8F1kRjMkO6ONm2vDWXkOKcYVNZcDAEh6tfKS3C0EKAnUbMRC2SS88Q7ffDOKIm9lKG2CpqtyLzGPC3suzAQ4EXxIcJjTlCJEleqFZOym16XEIOEqVSZPEc4L2ixYLu2Sq2m2zAXPNEn4J31GHBVKpjMx+5gzrYPXNjcHOWe9dgSGGFBqdoSvaTagMoyb0ovnGZmaikrhKt0EISnd1E/+Ir+ozlLDlODopiPwwlDVKnduC4JdZ6VSjDeCPoF5CCMJ/kyQ1DIIhuBqiD7NZ2donBFPAnDqC2mmkOpA7jBTCEmlQqrdmVCEKWTIFj89NUMxOpek86GibyckjC0Rhm+yY/Q9VE0wwjtAIAIaMMzPaL7UXFh0PHd8CrnWmsc2zdkzij0mJIhTyDET8zAMvGooDWxngpPcFbxDzAkGu4hLbZZwtQBBzXCt0u4gfR5HiINKcJYq7xFDMnjr1KwuCbM070gK6I8XWcYsRAQVFdJgEhqwy7kO2ssZRdHLjEodJ7X0BEkB22Y4814JU/xDJDgkloiEI0lxOZ/VFq11UusnVn0te0i5Q+PotFu5EF1I1WhcWlemakwESVVPWwonPagERbT5uTOzfiVeZ1TK5Wjx9b0ouifCWXdRXdJZONeSlAaklKBZUvt5V+qReo+XJ/TtIkMhxRm31Oxs4UIqx4CtgXdQZyiK05kFHxFmzDSrcxFgJaNqUdQ/2hSbEdZSyQXe/CTVVWC0Rd8HPaOQ5SBiXp/p3iIjfMVVEQP1ArodyxeXpYOl8Efq0lALMlaj/2EqAyIah81StxQArPmHcnMCCya3CCzTUMLSqC8oGUAX5QK1M/qeI8vfBdVcOBPgl0rTtFhVmM1udk6S9LWANUr6haECNnk9xJjh1RGInxz1gY82DUxsnNR605k8NKncuB3Y15DKLRMkwYlzKZNoAv7XNIplFIFTjtFudFkesq/4Tgx6+lZJOmdHQp20MeiYV20oK2hX50EyTZT0bZQ+KfI2mqrpAhowtObQYHhYTQ2fPtbIpjdGc0yC5V7Blq15Gw88ugLi7/OqRsY5rFOH0MKa5kb5GpzyXjB8IiC4bh7bWSsnAu0BGNKplXkdETT95JnzSrKsYVXaedLHCD3k2v7FOKY35YUR48jyJoLlk2sdeRT5/UKmZWEKSCIgK8FkvDZ5BTjj9UWc3/oXpeXd5f9r4f9jkCnvfv/9vw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [URL = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"URL\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e6401689-3f49-423f-bd1a-f05e55c1ccec"
          },
          {
            "name": "LinkedQueryName",
            "value": "Logo"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Month",
        "isHidden": true,
        "lineageTag": "b63e1b8f-fef4-4b9a-8582-18d05ae04fe4",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID",
            "formatString": "0",
            "lineageTag": "5f9da765-0454-42eb-9a6c-816ec7ee45a3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Month",
            "sortByColumn": "ID",
            "lineageTag": "82617bde-500c-4f3e-9ec3-291b2c5bace6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Month-18692bd2-081e-439c-860a-48a4b29964ea",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlfSUfJKzCtNLKpUitWJVrIA8t1Sk4rgApZAAd/EouQMMM/QAMh1LCjKzIFwDcGyEJWGRiCzSvNSY/JAJEQMLJQDUQCSdyxNLy0uAXONgdzg1IKS1Nyk1CKwiAlQxD+5JB/GNwXy/fLLEArMgAIuqclQgVgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [ID = _t, Month = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ID\", Int64.Type}, {\"Month\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"June#(lf)June\",\"June\",Replacer.ReplaceText,{\"Month\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c98ab75f-c83d-44a1-a4bf-4e032768be40"
          },
          {
            "name": "LinkedQueryName",
            "value": "Month"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Backorder Percentagee",
        "lineageTag": "f3c2f366-9b3b-482c-a99a-2b4e32ede62e",
        "columns": [
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "lineageTag": "2f6b93ce-0e82-4b14-b242-a04d84ac957a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "2a2aa740-9447-453e-88d4-e4b3366f66fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "Plant",
            "lineageTag": "d07bd344-e7ff-44f5-b9c4-30256ac7f8ac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Type",
            "dataType": "string",
            "sourceColumn": "Product Type",
            "lineageTag": "095bdcae-73bf-4812-b94f-6ec49548828d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Forecast Bias",
            "dataType": "string",
            "sourceColumn": "Forecast Bias",
            "lineageTag": "aa5fbcf4-863a-4ae3-a5ff-da05c7546d8d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Buyer Type",
            "dataType": "string",
            "sourceColumn": "Buyer Type",
            "lineageTag": "5292f879-2d26-4c24-8081-041a1beef9cd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Shipment Destination",
            "dataType": "string",
            "sourceColumn": "Shipment Destination",
            "lineageTag": "6c50b009-e0c5-4e60-bf11-ce0e8d399855",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Shipment Type",
            "dataType": "string",
            "sourceColumn": "Shipment Type",
            "lineageTag": "39d20270-3daf-42d6-82c4-4645d8d970c9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product ID",
            "lineageTag": "1258dcb8-ed90-4d72-866f-44c7c2048bdf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Forecast Accuracy",
            "dataType": "string",
            "sourceColumn": "Forecast Accuracy",
            "lineageTag": "d01878ac-80d3-4c10-b362-5dfa42cf2023",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "lineageTag": "d23ff730-0644-4036-854d-aa216677a6de",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Backorder %",
            "dataType": "double",
            "sourceColumn": "Backorder %",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6988337e-b59b-4f08-846b-610f1381bcd0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Distribution Center",
            "dataType": "string",
            "sourceColumn": "Distribution Center",
            "lineageTag": "b7007a7a-fa6c-41e3-96a1-b9996ba0afa6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Demand Type",
            "dataType": "string",
            "sourceColumn": "Demand Type",
            "lineageTag": "d125c68a-1120-4d74-9b4b-751bd993c3a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Backorder Percentagee-82de19c2-556d-430b-b59c-abf5ede0122a",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\juluczni\\Documents\\Backorders %.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Month\", type text}, {\"Region\", type text}, {\"Plant\", type text}, {\"Product Type\", type text}, {\"Forecast Bias\", type text}, {\"Buyer Type\", type text}, {\"Shipment Destination\", type text}, {\"Shipment Type\", type text}, {\"Product ID\", type text}, {\"Forecast Accuracy\", type text}, {\"Brand\", type text}, {\"Backorder %\", type number}, {\"Distribution Center\", type text}, {\"Demand Type\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "% on backorder",
            "expression": "AVERAGE('Backorder Percentagee'[Backorder %])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ab33b318-a53a-48c2-b573-8758a887efe7"
          },
          {
            "name": "Backorder $",
            "expression": "sum('Backorder Percentagee'[Backorder %]) * 10000",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4b6a9dfe-e7a9-405d-8e40-3ca91c9a7089",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Product Availability",
            "expression": "AVERAGE('Backorder Percentagee'[Backorder %]) * 15",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "37a558fc-15c2-4b74-935a-5cf46e3a1b4a"
          },
          {
            "name": "% on time orders",
            "expression": "AVERAGE('Backorder Percentagee'[Backorder %])",
            "lineageTag": "4e8b4aeb-12c7-4653-b3db-8d2682262a15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "35f96540-460a-4ca8-8839-8caefc199959"
          },
          {
            "name": "LinkedQueryName",
            "value": "Backorder Percentage"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":14,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Backorder Percentage/Changed Type.{Month,0}\",\"Section1/Backorder Percentage/Changed Type.{Region,1}\",\"Section1/Backorder Percentage/Changed Type.{Plant,2}\",\"Section1/Backorder Percentage/Changed Type.{Product Type,3}\",\"Section1/Backorder Percentage/Changed Type.{Forecast Bias,4}\",\"Section1/Backorder Percentage/Changed Type.{Buyer Type,5}\",\"Section1/Backorder Percentage/Changed Type.{Shipment Destination,6}\",\"Section1/Backorder Percentage/Changed Type.{Shipment Type,7}\",\"Section1/Backorder Percentage/Changed Type.{Product ID,8}\",\"Section1/Backorder Percentage/Changed Type.{Forecast Accuracy,9}\",\"Section1/Backorder Percentage/Changed Type.{Brand,10}\",\"Section1/Backorder Percentage/Changed Type.{Backorder %,11}\",\"Section1/Backorder Percentage/Changed Type.{Distribution Center,12}\",\"Section1/Backorder Percentage/Changed Type.{Demand Type,13}\"],\"ColumnCount\":14,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Backorder Percentage/Changed Type.{Month,0}\",\"Section1/Backorder Percentage/Changed Type.{Region,1}\",\"Section1/Backorder Percentage/Changed Type.{Plant,2}\",\"Section1/Backorder Percentage/Changed Type.{Product Type,3}\",\"Section1/Backorder Percentage/Changed Type.{Forecast Bias,4}\",\"Section1/Backorder Percentage/Changed Type.{Buyer Type,5}\",\"Section1/Backorder Percentage/Changed Type.{Shipment Destination,6}\",\"Section1/Backorder Percentage/Changed Type.{Shipment Type,7}\",\"Section1/Backorder Percentage/Changed Type.{Product ID,8}\",\"Section1/Backorder Percentage/Changed Type.{Forecast Accuracy,9}\",\"Section1/Backorder Percentage/Changed Type.{Brand,10}\",\"Section1/Backorder Percentage/Changed Type.{Backorder %,11}\",\"Section1/Backorder Percentage/Changed Type.{Distribution Center,12}\",\"Section1/Backorder Percentage/Changed Type.{Demand Type,13}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_ChangedProperties",
            "value": "[\"Name\"]"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "f1f4dec2-922f-4ec6-8dc1-49554a10a01c",
        "fromTable": "Explanations",
        "fromColumn": "Product ID",
        "toTable": "Risk",
        "toColumn": "Product ID"
      },
      {
        "name": "9ed0ec75-78b2-4f82-bffb-1dce5fda3499",
        "fromTable": "Backorder Percentagee",
        "fromColumn": "Month",
        "toTable": "Month",
        "toColumn": "Month"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "2.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "supply_analytics": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "supply analytics": {
                      "State": "Generated"
                    }
                  },
                  {
                    "analytics": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "supply_analytics.manufactured_goods_": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Manufactured Goods %"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "manufactured goods %": {
                      "State": "Generated"
                    }
                  },
                  {
                    "manufactured goods percentage": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7615384413645817
                    }
                  },
                  {
                    "manufactured goods pct": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7386922881236443
                    }
                  }
                ]
              },
              "supply_analytics.forecast_accuracy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Forecast Accuracy"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "forecast accuracy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "accuracy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "prediction accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "projection accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "report accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "estimate accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "forecast correctness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "forecast accurateness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "forecast exactness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "forecast truth": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999869868209
                    }
                  },
                  {
                    "forecast truthfulness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999819868207
                    }
                  },
                  {
                    "forecast exactitude": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999769868205
                    }
                  }
                ]
              },
              "supply_analytics.forecast_bias": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Forecast Bias"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "forecast bias": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bias": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "prediction bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "projection bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "report bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "estimate bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "forecast partiality": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "forecast unfairness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "forecast favoritism": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "forecast predisposition": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999869868209
                    }
                  },
                  {
                    "forecast preconception": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999819868207
                    }
                  },
                  {
                    "forecast preference": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999769868205
                    }
                  }
                ]
              },
              "supply_analytics.product_advertised": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Product Advertised"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "product advertised": {
                      "State": "Generated"
                    }
                  },
                  {
                    "artifact advertised": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "item advertised": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "merchandise advertised": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "produce advertised": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  }
                ]
              },
              "supply_analytics.multiple_retailer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Multiple Retailers"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "multiple retailer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "retailer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "multiple seller": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "multiple vender": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "multiple vendor": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999869868209
                    }
                  },
                  {
                    "multiple trader": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999769868205
                    }
                  },
                  {
                    "multiple dealer": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999971986820296
                    }
                  },
                  {
                    "seller": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090613251546
                    }
                  },
                  {
                    "vender": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090122342435
                    }
                  },
                  {
                    "vendor": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909089631433325
                    }
                  },
                  {
                    "trader": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49090886496151037
                    }
                  },
                  {
                    "dealer": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909088158705993
                    }
                  }
                ]
              },
              "supply_analytics.day_contacted": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Day Contacted"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "day contacted": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "supply_analytics.product": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Product "
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "product": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Claims Amount": {
                      "State": "Generated",
                      "Source": {
                        "Type": "External",
                        "Agent": "PowerBI.VisualColumnRename"
                      },
                      "Weight": 0.873
                    }
                  },
                  {
                    "Claim Amount": {
                      "Type": "Noun",
                      "State": "Generated",
                      "Weight": 0.68094
                    }
                  },
                  {
                    "artifact": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "item": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "merchandise": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "produce": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "claim quantity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "claim volume": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "claim expanse": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999869868209
                    }
                  },
                  {
                    "claim extent": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999819868207
                    }
                  },
                  {
                    "claim sum": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  },
                  {
                    "claim total": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.48499997077216667
                    }
                  }
                ]
              },
              "supply_analytics.manufactured": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Manufactured (%)"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "manufactured": {
                      "State": "Generated"
                    }
                  },
                  {
                    "manufactured (%)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mass-produced": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "industrial": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "manmade": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  },
                  {
                    "man-made": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816942490325
                    }
                  },
                  {
                    "synthetic": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816466308488
                    }
                  },
                  {
                    "artificial": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618159901266505
                    }
                  },
                  {
                    "contrived": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  },
                  {
                    "affected": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4523727000111299
                    }
                  },
                  {
                    "insincere": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4523726547738554
                    }
                  },
                  {
                    "pretend": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237260953658087
                    }
                  }
                ],
                "Units": [
                  "percentage",
                  "%"
                ]
              },
              "supply_analytics.inventory_level": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Inventory Levels"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "inventory level": {
                      "State": "Generated"
                    }
                  },
                  {
                    "level": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "inventory quantity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "inventory threshold": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "threshold": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "inventory amount": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "inventory grade": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "inventory point": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "inventory rank": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "inventory tier": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "grade": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "point": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  }
                ]
              },
              "supply_analytics.manufactured_goods": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Manufactured Goods"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "manufactured goods": {
                      "State": "Generated"
                    }
                  },
                  {
                    "goods": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "manufactured property": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "manufactured thing": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "manufactured possession": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "property": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "thing": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090613251546
                    }
                  },
                  {
                    "possession": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090122342435
                    }
                  },
                  {
                    "manufactured belonging": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  },
                  {
                    "belonging": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "manufactured commodity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4749999238748004
                    }
                  },
                  {
                    "manufactured cargo": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4749998763747985
                    }
                  }
                ]
              },
              "supply_analytics.demand_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Demand Type"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "demand type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "demand category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "demand genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "demand manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "demand variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "demand brand": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "demand class": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  }
                ]
              },
              "supply_analytics.manufactured_goods1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Manufactured Goods (%)"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "manufactured goods": {
                      "State": "Generated"
                    }
                  },
                  {
                    "manufactured goods (%)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "goods": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "manufactured property": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "manufactured thing": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "manufactured possession": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "property": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "thing": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090613251546
                    }
                  },
                  {
                    "possession": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090122342435
                    }
                  },
                  {
                    "manufactured belonging": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  },
                  {
                    "belonging": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "manufactured commodity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4749999238748004
                    }
                  },
                  {
                    "manufactured cargo": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4749998763747985
                    }
                  }
                ],
                "Units": [
                  "percentage",
                  "%"
                ]
              },
              "supply_analytics.type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Type"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "class": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "kind": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "style": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "form": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "grouping": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  }
                ]
              },
              "supply_analytics.plant": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Supply Analytics",
                    "ConceptualProperty": "Plant"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "plant": {
                      "State": "Generated"
                    }
                  },
                  {
                    "vegetable": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "herbal": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "shrub": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663636548952623
                    }
                  },
                  {
                    "houseplant": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663634683498003
                    }
                  },
                  {
                    "seedling": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663633750770693
                    }
                  },
                  {
                    "bush": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  },
                  {
                    "flower": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4523727000111299
                    }
                  },
                  {
                    "herb": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4523726547738554
                    }
                  },
                  {
                    "cutting": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237251906203185
                    }
                  }
                ]
              },
              "risk": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Risk"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "risk": {
                      "State": "Generated"
                    }
                  },
                  {
                    "danger": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "jeopardy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "peril": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "hazard": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  },
                  {
                    "menace": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816942490325
                    }
                  },
                  {
                    "threat": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816466308488
                    }
                  },
                  {
                    "possibility": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663636548952623
                    }
                  },
                  {
                    "probability": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663634683498003
                    }
                  },
                  {
                    "consequence": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663633750770693
                    }
                  },
                  {
                    "chance": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  }
                ]
              },
              "risk.product_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Risk",
                    "ConceptualProperty": "Product ID"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "product ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product identification": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product identity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product identifier": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "artifact": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "product credential": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "item": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "merchandise": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "produce": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "artifact id": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "item id": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  }
                ]
              },
              "risk.location": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Risk",
                    "ConceptualProperty": "Location"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "location": {
                      "State": "Generated"
                    }
                  },
                  {
                    "locality": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "placement": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "scene": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "venue": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "address": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "place": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "position": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "setting": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "site": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "spot": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  }
                ]
              },
              "risk.risk_score": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Risk",
                    "ConceptualProperty": "Risk Score"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "risk score": {
                      "State": "Generated"
                    }
                  },
                  {
                    "score": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "risk notch": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  },
                  {
                    "risk slash": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  },
                  {
                    "risk groove": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.48499997077216667
                    }
                  },
                  {
                    "risk nick": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.48499992227216454
                    }
                  },
                  {
                    "risk cut": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4849998737721627
                    }
                  },
                  {
                    "risk mark": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4849998252721608
                    }
                  },
                  {
                    "notch": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "slash": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "groove": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "nick": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  }
                ]
              },
              "risk.backorder_risk": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Risk",
                    "ConceptualProperty": "Backorder Risk"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "backorder risk": {
                      "State": "Generated"
                    }
                  },
                  {
                    "risk": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "backorder danger": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "backorder jeopardy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "danger": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "jeopardy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "backorder peril": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.48499997077216667
                    }
                  },
                  {
                    "backorder hazard": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.48499992227216454
                    }
                  },
                  {
                    "backorder menace": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4849998737721627
                    }
                  },
                  {
                    "backorder threat": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4849998252721608
                    }
                  },
                  {
                    "peril": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "hazard": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  }
                ]
              },
              "risk.distribution_center": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Risk",
                    "ConceptualProperty": "Distribution Center"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "distribution center": {
                      "State": "Generated"
                    }
                  },
                  {
                    "center": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "distribution midpoint": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "distribution epicenter": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "midpoint": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "epicenter": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090122342435
                    }
                  },
                  {
                    "distribution middle": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  },
                  {
                    "distribution focus": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.48499997077216667
                    }
                  },
                  {
                    "middle": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "focus": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "distribution region": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4749999713748023
                    }
                  },
                  {
                    "distribution heart": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46075001830856005
                    }
                  }
                ]
              },
              "explanation": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Explanations"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "explanation": {
                      "State": "Generated"
                    }
                  },
                  {
                    "clarification": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "description": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "elucidation": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090613251546
                    }
                  },
                  {
                    "enlightenment": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909089631433325
                    }
                  },
                  {
                    "account": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  },
                  {
                    "justification": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46636360825889683
                    }
                  },
                  {
                    "rationalization": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46636356162253134
                    }
                  },
                  {
                    "vindication": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663634683498003
                    }
                  },
                  {
                    "reason": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  },
                  {
                    "excuse": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237251906203185
                    }
                  }
                ]
              },
              "explanation.product_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Explanations",
                    "ConceptualProperty": "Product ID"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "product ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product identification": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product identity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product identifier": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "artifact": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "product credential": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "item": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "merchandise": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "produce": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "artifact id": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "item id": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  }
                ]
              },
              "explanation.location": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Explanations",
                    "ConceptualProperty": "Location"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "location": {
                      "State": "Generated"
                    }
                  },
                  {
                    "locality": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "placement": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "scene": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "venue": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "address": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "place": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "position": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "setting": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "site": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "spot": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  }
                ]
              },
              "explanation.factor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Explanations",
                    "ConceptualProperty": "Factor"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "factor": {
                      "State": "Generated"
                    }
                  },
                  {
                    "aspect": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090122342435
                    }
                  },
                  {
                    "element": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909088158705993
                    }
                  },
                  {
                    "thing": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909087667796883
                    }
                  },
                  {
                    "consideration": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49090871768877725
                    }
                  },
                  {
                    "issue": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "influence": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "feature": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "reason": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816942490325
                    }
                  },
                  {
                    "cause": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816466308488
                    }
                  },
                  {
                    "dynamic": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618159901266505
                    }
                  }
                ]
              },
              "explanation.risk": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Explanations",
                    "ConceptualProperty": "Risk"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "risk": {
                      "State": "Generated"
                    }
                  },
                  {
                    "danger": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "jeopardy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "peril": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "hazard": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  },
                  {
                    "menace": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816942490325
                    }
                  },
                  {
                    "threat": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816466308488
                    }
                  },
                  {
                    "possibility": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663636548952623
                    }
                  },
                  {
                    "probability": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663634683498003
                    }
                  },
                  {
                    "consequence": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663633750770693
                    }
                  },
                  {
                    "chance": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  }
                ]
              },
              "logo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Logo"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "logo": {
                      "State": "Generated"
                    }
                  },
                  {
                    "emblem": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090613251546
                    }
                  },
                  {
                    "symbol": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "sign": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "badge": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  },
                  {
                    "insigne": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816942490325
                    }
                  },
                  {
                    "design": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816466308488
                    }
                  }
                ]
              },
              "logo.url": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Logo",
                    "ConceptualProperty": "URL"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "url": {
                      "State": "Generated"
                    }
                  },
                  {
                    "website": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "site": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "web address": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5714181666807695
                    }
                  }
                ]
              },
              "month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Month"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mth": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  }
                ]
              },
              "month.ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Month",
                    "ConceptualProperty": "ID"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "identification": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "identity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "credential": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  }
                ]
              },
              "month.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Month",
                    "ConceptualProperty": "Month"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mth": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  }
                ]
              },
              "backorder_percentage": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "backorder percentage": {}
                  },
                  {
                    "percentage": {
                      "Weight": 0.97
                    }
                  },
                  {
                    "order": {}
                  },
                  {
                    "backorder ratio": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "backorder measurement": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999819868207
                    }
                  },
                  {
                    "backorder calculation": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999769868205
                    }
                  },
                  {
                    "instruction": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "ratio": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090613251546
                    }
                  },
                  {
                    "direction": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090122342435
                    }
                  },
                  {
                    "measurement": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49090891405242143
                    }
                  },
                  {
                    "calculation": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49090886496151037
                    }
                  },
                  {
                    "edict": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49090886496151037
                    }
                  },
                  {
                    "backorder fraction": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  }
                ]
              },
              "backorder_percentage.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Month"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mth": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  }
                ]
              },
              "backorder_percentage.region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Region"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "region": {
                      "State": "Generated"
                    }
                  },
                  {
                    "territory": {
                      "LastModified": "2020-01-27T20:34:19.1747697Z"
                    }
                  },
                  {
                    "province": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "area": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "district": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "section": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "zone": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "continent": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "terrain": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "land": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "ground": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "place": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618159901266505
                    }
                  }
                ]
              },
              "backorder_percentage.plant": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Plant"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "plant": {
                      "State": "Generated"
                    }
                  },
                  {
                    "vegetable": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "herbal": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "shrub": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663636548952623
                    }
                  },
                  {
                    "houseplant": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663634683498003
                    }
                  },
                  {
                    "seedling": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663633750770693
                    }
                  },
                  {
                    "bush": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  },
                  {
                    "flower": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4523727000111299
                    }
                  },
                  {
                    "herb": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4523726547738554
                    }
                  },
                  {
                    "cutting": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237251906203185
                    }
                  }
                ]
              },
              "backorder_percentage.product_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Product Type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "product brand": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "product class": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  }
                ]
              },
              "backorder_percentage.forecast_bias": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Forecast Bias"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "forecast bias": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bias": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "prediction bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "projection bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "report bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "estimate bias": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "forecast partiality": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "forecast unfairness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "forecast favoritism": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "forecast predisposition": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999869868209
                    }
                  },
                  {
                    "forecast preconception": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999819868207
                    }
                  },
                  {
                    "forecast preference": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999769868205
                    }
                  }
                ]
              },
              "backorder_percentage.buyer_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Buyer Type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "buyer type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "buyer category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "buyer genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "buyer manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "buyer variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "buyer brand": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "buyer class": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  }
                ]
              },
              "backorder_percentage.shipment_destination": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Shipment Destination"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "shipment destination": {
                      "State": "Generated"
                    }
                  },
                  {
                    "destination": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "shipment intention": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4749997813747948
                    }
                  },
                  {
                    "intention": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663634217134349
                    }
                  },
                  {
                    "shipment purpose": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46075001830856005
                    }
                  },
                  {
                    "shipment end": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46075001830856005
                    }
                  },
                  {
                    "shipment target": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46074997223355824
                    }
                  },
                  {
                    "shipment aim": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46074992615855637
                    }
                  },
                  {
                    "shipment goal": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46074988008355455
                    }
                  },
                  {
                    "shipment objective": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46074983400855274
                    }
                  },
                  {
                    "purpose": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  },
                  {
                    "end": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.45237274524840443
                    }
                  }
                ]
              },
              "backorder_percentage.shipment_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Shipment Type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "shipment type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "shipment category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "shipment genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "shipment manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "shipment variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "shipment brand": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "shipment class": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  }
                ]
              },
              "backorder_percentage.product_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Product ID"
                  }
                },
                "State": "Generated",
                "Hidden": true,
                "Terms": [
                  {
                    "product ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product identification": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product identity": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "product identifier": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "artifact": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "product credential": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "item": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "merchandise": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "produce": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7142727083509619
                    }
                  },
                  {
                    "artifact id": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "item id": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  }
                ]
              },
              "backorder_percentage.forecast_accuracy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Forecast Accuracy"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "forecast accuracy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "accuracy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "prediction accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "projection accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "report accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "estimate accuracy": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "forecast correctness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "forecast accurateness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "forecast exactness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "forecast truth": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999869868209
                    }
                  },
                  {
                    "forecast truthfulness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999819868207
                    }
                  },
                  {
                    "forecast exactitude": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999769868205
                    }
                  }
                ]
              },
              "backorder_percentage.brand": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Brand"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "brand": {
                      "State": "Generated"
                    }
                  },
                  {
                    "variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090613251546
                    }
                  },
                  {
                    "marque": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49090886496151037
                    }
                  },
                  {
                    "make": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "kind": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761817418672162
                    }
                  },
                  {
                    "trademark": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761816466308488
                    }
                  },
                  {
                    "style": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618150377629764
                    }
                  },
                  {
                    "class": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761814561581139
                    }
                  },
                  {
                    "strain": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4761814085399302
                    }
                  },
                  {
                    "cast": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618136092174645
                    }
                  },
                  {
                    "marker": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4663636548952623
                    }
                  }
                ]
              },
              "backorder_percentage.backorder_": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Backorder %"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "backorder %": {
                      "State": "Generated"
                    }
                  },
                  {
                    "backorder pct": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  }
                ]
              },
              "backorder_percentage.distribution_center": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Distribution Center"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "distribution center": {
                      "State": "Generated"
                    }
                  },
                  {
                    "center": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "distribution midpoint": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "distribution epicenter": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "midpoint": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909091104160656
                    }
                  },
                  {
                    "epicenter": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4909090122342435
                    }
                  },
                  {
                    "distribution middle": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4850000192721685
                    }
                  },
                  {
                    "distribution focus": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.48499997077216667
                    }
                  },
                  {
                    "middle": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618183710358364
                    }
                  },
                  {
                    "focus": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.47618178948539996
                    }
                  },
                  {
                    "distribution region": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4749999713748023
                    }
                  },
                  {
                    "distribution heart": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.46075001830856005
                    }
                  }
                ]
              },
              "backorder_percentage.demand_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Demand Type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "demand type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "demand category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "demand genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "demand manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "demand variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  },
                  {
                    "category": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "genre": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "manner": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "variety": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7363636168566617
                    }
                  },
                  {
                    "demand brand": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "demand class": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7274999807278316
                    }
                  },
                  {
                    "Segment": {
                      "State": "Suggested",
                      "Source": {
                        "Type": "External",
                        "Agent": "PowerBI.VisualColumnRename"
                      },
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "backorder_percentage.on_backorder": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "% on backorder"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "% on backorder": {
                      "State": "Generated"
                    }
                  },
                  {
                    "percentage on backorder": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7615384413645817
                    }
                  },
                  {
                    "pct on backorder": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7386922881236443
                    }
                  }
                ]
              },
              "backorder_percentage.backorder_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Backorder $"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "backorder $": {
                      "State": "Generated"
                    }
                  },
                  {
                    "backorder dollar": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7499999801317851
                    }
                  }
                ]
              },
              "backorder_percentage.product_availability": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "Product Availability"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product availability": {
                      "State": "Generated"
                    }
                  },
                  {
                    "availability": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact availability": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5999999841054281
                    }
                  },
                  {
                    "item availability": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "merchandise availability": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "produce availability": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5819999845822653
                    }
                  },
                  {
                    "product obtainability": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "product handiness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.500000019868215
                    }
                  },
                  {
                    "product accessibility": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.49999996986821305
                    }
                  },
                  {
                    "product convenience": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.4999999198682109
                    }
                  },
                  {
                    "product readiness": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999869868209
                    }
                  },
                  {
                    "product disposal": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.499999819868207
                    }
                  }
                ]
              },
              "backorder_percentage.on_time_orders": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Backorder Percentagee",
                    "ConceptualProperty": "% on time orders"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "% on time orders": {
                      "State": "Generated"
                    }
                  },
                  {
                    "percentage on time order": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7714285509926931
                    }
                  },
                  {
                    "pct on time order": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.7482856944629124
                    }
                  },
                  {
                    "% on duration order": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.6171428407941546
                    }
                  },
                  {
                    "% on interval order": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.6171428407941546
                    }
                  },
                  {
                    "% on moment order": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.6171428407941546
                    }
                  },
                  {
                    "% on period order": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5986285555703299
                    }
                  },
                  {
                    "% on timetable order": {
                      "Type": "Noun",
                      "State": "Suggested",
                      "Weight": 0.5986285555703299
                    }
                  }
                ]
              }
            },
            "Relationships": {
              "backorder_percentage_in_region": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.region": {
                    "Target": {
                      "Entity": "backorder_percentage.region"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "backorder_percentage.region"
                  }
                },
                "Phrasings": [
                  {
                    "Preposition": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Prepositions": [
                        {
                          "in": {}
                        }
                      ],
                      "Object": {
                        "Role": "backorder_percentage.region"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_month": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.month": {
                    "Target": {
                      "Entity": "backorder_percentage.month"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.month"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_region": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.region": {
                    "Target": {
                      "Entity": "backorder_percentage.region"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.region"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_plant": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.plant": {
                    "Target": {
                      "Entity": "backorder_percentage.plant"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.plant"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_product_type": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.product_type": {
                    "Target": {
                      "Entity": "backorder_percentage.product_type"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.product_type"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_forecast_bias": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.forecast_bias": {
                    "Target": {
                      "Entity": "backorder_percentage.forecast_bias"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.forecast_bias"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_buyer_type": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.buyer_type": {
                    "Target": {
                      "Entity": "backorder_percentage.buyer_type"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.buyer_type"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_shipment_destination": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.shipment_destination": {
                    "Target": {
                      "Entity": "backorder_percentage.shipment_destination"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.shipment_destination"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_shipment_type": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.shipment_type": {
                    "Target": {
                      "Entity": "backorder_percentage.shipment_type"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.shipment_type"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_forecast_accuracy": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.forecast_accuracy": {
                    "Target": {
                      "Entity": "backorder_percentage.forecast_accuracy"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.forecast_accuracy"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_brand": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.brand": {
                    "Target": {
                      "Entity": "backorder_percentage.brand"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.brand"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_backorder_": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.backorder_": {
                    "Target": {
                      "Entity": "backorder_percentage.backorder_"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.backorder_"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_distribution_center": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.distribution_center": {
                    "Target": {
                      "Entity": "backorder_percentage.distribution_center"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.distribution_center"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_demand_type": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.demand_type": {
                    "Target": {
                      "Entity": "backorder_percentage.demand_type"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.demand_type"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_on_backorder": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.on_backorder": {
                    "Target": {
                      "Entity": "backorder_percentage.on_backorder"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.on_backorder"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_backorder_1": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.backorder_1": {
                    "Target": {
                      "Entity": "backorder_percentage.backorder_1"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.backorder_1"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_product_availability": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.product_availability": {
                    "Target": {
                      "Entity": "backorder_percentage.product_availability"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.product_availability"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_on_time_orders": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.on_time_orders": {
                    "Target": {
                      "Entity": "backorder_percentage.on_time_orders"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.on_time_orders"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "backorder_percentage_has_claims": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "backorder_percentage.claims": {
                    "Target": {
                      "Entity": "backorder_percentage.claims"
                    }
                  }
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Subject": {
                        "Role": "backorder_percentage"
                      },
                      "Object": {
                        "Role": "backorder_percentage.claims"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ]
              },
              "explanation_has_risk": {
                "Binding": {
                  "ConceptualEntity": "Explanations"
                },
                "State": "Generated",
                "Roles": {
                  "explanation": {
                    "Target": {
                      "Entity": "explanation"
                    }
                  },
                  "risk": {
                    "Target": {
                      "Entity": "risk"
                    }
                  }
                }
              },
              "backorder_percentage_has_month1": {
                "Binding": {
                  "ConceptualEntity": "Backorder Percentagee"
                },
                "State": "Generated",
                "Roles": {
                  "backorder_percentage": {
                    "Target": {
                      "Entity": "backorder_percentage"
                    }
                  },
                  "month": {
                    "Target": {
                      "Entity": "month"
                    }
                  }
                }
              }
            }
          },
          "contentType": "json"
        }
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.104.941.0 (22.04)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Supply Analytics\",\"Risk\",\"Explanations\",\"Logo\",\"Month\",\"Backorder Percentagee\"]"
      }
    ]
  }
}
