name: CD
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
      choice:
        type: choice
        description: Release/Deploy Choose the environment to deploy in.
        options:
        - Test Workspace
        - Prod Workspace
        required: true
      notify:
        description: 'Fill out an email to let him know about your great work! (Teams or Email Notification)'     
        required: false      
      datasource:
        description: 'Update your datasource, fill in your string connection'    
        required: false
jobs:
  build:
    runs-on: windows-latest
    environment: MyEnvironment
    name: PowerBI CD
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: poocuser/MainDeserialization@main
        with:
          environment: MyEnvironment
          ENVIRONMENT_EVENT: ${{ github.event.inputs.environment }}
          CHOICE: ${{ github.event.inputs.choice }}
          NOTIFY: ${{ github.event.inputs.notify }}
          PBI_PREMIUM_WORKSPACE_ID: ${{ secrets.PBI_PREMIUM_WORKSPACE_ID }}
          PBI_TENANT_ID: ${{ secrets.PBI_TENANT_ID }}
          PBI_CLIENT_ID: ${{ secrets.PBI_CLIENT_ID }}
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
          PROJECT_NAME: "TDF1"
          PREMIUM: "false"
          USER_EMAIL: "poocuser@6ysf6f.onmicrosoft.com"