name: CD
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: false
      choice:
        type: choice
        description: Release/Deploy (Make sure the last version exists in the test workspace otherwise the workflow will fail)
        options:
        - Test Workspace
        - Prod Workspace
        required: true
      notify:
        description: 'Fill in an email to notify someone of your great work!'     
        required: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: poocuser/MainDeserialization@main
        with:
          ENVIRONMENT_EVENT: ${{ github.event.inputs.environment }}
          CHOICE: ${{ github.event.inputs.choice }}
          NOTIFY: ${{ github.event.inputs.notify }}