on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v12
        with:
          separator: ","
      #- name: GET DIFF FILES
        #id: GET_DIFF_FILES
        #env:
          #GIT_EVENT_BEFORE: ${{ github.event.before }}
          #GIT_EVENT_AFTER: ${{ github.event.after }}
          #GIT_TRIGGER_NAME: ${{ github.event_name }}
        #run: |
          #echo ::set-output name=filesList::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
      - id: foo
        uses: poocuser/MainDeserialization@main
        with:
          who-to-greet: 'Amine Bounizel6'
          files: ${{ steps.changed-files.outputs.all_modified_files }} #${{steps.GET_DIFF_FILES.outputs.filesList}} 
          separator: ","
          composite-path: ${{ github.workspace }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash  
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Reformatted JSON Outputs