name: CI-Main
on:
  push:
    branches: [main]
jobs:
  Reformat-PBIX-Files:
    runs-on: ubuntu-latest
    steps:
        - name: ReportExtractorf
          uses: poocuser/ExtractReportMain@main
  Reformat-PBIX-Files2:
    runs-on: windows-latest
    steps:
        - name: ModelExtractor
          uses: poocuser/ExtractModelMain@main