on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v12
        with:
          separator: ","
      - id: foo
        uses: poocuser/MainDeserialization@main
        with:
          who-to-greet: 'Amine Bounizel6'
          files: ${{ steps.changed-files.outputs.all_modified_files }}
          separator: ","
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash